@echo off
REM ============================================================================
REM Momentum Trader Charts - Smart Desktop Launcher for Windows
REM ============================================================================
REM
REM This file can be copied ANYWHERE (Desktop, Documents, etc.) and will work!
REM Auto-detects both the charting app and momentum-trader project locations.
REM
REM If auto-detection fails, edit the paths below.
REM ============================================================================

SETLOCAL EnableDelayedExpansion

REM ============================================================================
REM MANUAL OVERRIDE (optional - leave empty for auto-detection)
REM ============================================================================
REM Example: SET CHARTING_DIR=C:\Users\YourName\trading-projects\momentum-trader-charting
REM Example: SET MOMENTUM_DIR=C:\Users\YourName\trading-projects\momentum-trader
SET CHARTING_DIR=
SET MOMENTUM_DIR=

echo ===================================================================
echo Momentum Trader Charts - Desktop Launcher
echo ===================================================================
echo.

REM ============================================================================
REM AUTO-DETECTION: Find charting app
REM ============================================================================

IF NOT "%CHARTING_DIR%"=="" (
    echo Using configured charting path...
    goto :find_momentum
)

echo Auto-detecting charting app location...

FOR %%D IN (
    "%USERPROFILE%\trading-projects\momentum-trader-charting"
    "%USERPROFILE%\Documents\trading-projects\momentum-trader-charting"
    "%USERPROFILE%\momentum-trader-charting"
    "%USERPROFILE%\Documents\momentum-trader-charting"
    "%USERPROFILE%\Desktop\momentum-trader-charting"
    "C:\trading-projects\momentum-trader-charting"
    "C:\Users\%USERNAME%\trading-projects\momentum-trader-charting"
    "C:\momentum-trader-charting"
    "D:\trading-projects\momentum-trader-charting"
    "D:\momentum-trader-charting"
) DO (
    IF EXIST "%%~D\backend\main.py" (
        SET "CHARTING_DIR=%%~D"
        echo   Found charting app: !CHARTING_DIR!
        goto :find_momentum
    )
)

echo   [ERROR] Could not find charting app
goto :error_charting_not_found

REM ============================================================================
REM AUTO-DETECTION: Find momentum-trader
REM ============================================================================

:find_momentum
echo.

IF NOT "%MOMENTUM_DIR%"=="" (
    echo Using configured momentum-trader path...
    goto :verify_directories
)

echo Auto-detecting momentum-trader location...

FOR %%D IN (
    "%USERPROFILE%\trading-projects\momentum-trader"
    "%USERPROFILE%\Documents\trading-projects\momentum-trader"
    "%USERPROFILE%\momentum-trader"
    "%USERPROFILE%\Documents\momentum-trader"
    "%USERPROFILE%\Desktop\momentum-trader"
    "C:\trading-projects\momentum-trader"
    "C:\Users\%USERNAME%\trading-projects\momentum-trader"
    "C:\momentum-trader"
    "D:\trading-projects\momentum-trader"
    "D:\momentum-trader"
) DO (
    IF EXIST "%%~D\launcher.py" (
        SET "MOMENTUM_DIR=%%~D"
        echo   Found momentum-trader: !MOMENTUM_DIR!
        goto :verify_directories
    )
)

echo   [ERROR] Could not find momentum-trader
goto :error_momentum_not_found

REM ============================================================================
REM VERIFY DIRECTORIES
REM ============================================================================

:verify_directories
echo.
echo Verifying projects...

REM Verify charting app
IF NOT EXIST "%CHARTING_DIR%\backend\main.py" (
    echo   [ERROR] Charting app backend not found
    goto :error_charting_not_found
)
echo   Charting app: OK

REM Verify momentum-trader data directory
IF NOT EXIST "%MOMENTUM_DIR%\data" (
    echo   [WARNING] momentum-trader data directory not found
    echo   Creating: %MOMENTUM_DIR%\data
    mkdir "%MOMENTUM_DIR%\data" 2>nul
)
echo   Momentum-trader: OK
echo.

REM ============================================================================
REM UPDATE CONFIG: Write momentum-trader path to charting.yaml
REM ============================================================================

echo Updating charting configuration...

REM Create config directory if it doesn't exist
IF NOT EXIST "%CHARTING_DIR%\config" (
    mkdir "%CHARTING_DIR%\config"
)

REM Convert backslashes to forward slashes for YAML compatibility
REM (Backslashes in YAML strings are treated as escape sequences)
SET "MOMENTUM_DIR_YAML=%MOMENTUM_DIR:\=/%"
SET "CHARTING_DIR_YAML=%CHARTING_DIR:\=/%"

REM Write the config file with absolute paths (using forward slashes)
(
echo # Momentum Trader Charting App Configuration
echo # Auto-generated by startup script - paths are absolute
echo app:
echo   name: "Momentum Trader Charts"
echo   version: "1.0.0"
echo.
echo data_sources:
echo   momentum_trader:
echo     data_dir: "!MOMENTUM_DIR_YAML!/data"
echo     api_url: "http://localhost:8080"
echo     poll_interval_ms: 5000
echo.
echo   schwab:
echo     credentials_path: "!MOMENTUM_DIR_YAML!/config/credentials.yaml"
echo     tokens_path: "!MOMENTUM_DIR_YAML!/data/tokens/schwab_tokens.json"
echo     read_only: true
echo.
echo charts:
echo   default_timeframe: "1m"
echo   available_timeframes: ["1m", "5m", "15m", "D"]
echo   max_candles: 500
echo.
echo layout:
echo   primary_chart_ratio: 0.6
echo   secondary_grid: "2x2"
echo   heatmap_height: 80
) > "%CHARTING_DIR%\config\charting.yaml"

echo   Config updated: %CHARTING_DIR%\config\charting.yaml
echo   Data directory: %MOMENTUM_DIR%\data
echo.

REM ============================================================================
REM ACTIVATE VENV AND START BACKEND
REM ============================================================================

echo Starting charting backend...
echo.

cd /d "%CHARTING_DIR%\backend"

REM Check if venv exists
IF NOT EXIST "venv\Scripts\activate.bat" (
    echo   [ERROR] Virtual environment not found
    echo.
    echo   Please run setup first:
    echo     cd %CHARTING_DIR%\backend
    echo     python -m venv venv
    echo     venv\Scripts\activate
    echo     pip install -r requirements.txt
    echo.
    pause
    exit /b 1
)

REM Activate venv and run
call venv\Scripts\activate.bat
python main.py

REM Check exit code
IF ERRORLEVEL 1 (
    echo.
    echo ===================================================================
    echo Application failed to start
    echo ===================================================================
    echo See error messages above for details
    echo.
    pause
    exit /b 1
)

exit /b 0

REM ============================================================================
REM ERROR: Charting app not found
REM ============================================================================

:error_charting_not_found
echo.
echo ===================================================================
echo ERROR: Momentum Trader Charts not found
echo ===================================================================
echo.
echo Searched these locations:
echo   %USERPROFILE%\trading-projects\momentum-trader-charting
echo   %USERPROFILE%\Documents\trading-projects\momentum-trader-charting
echo   %USERPROFILE%\momentum-trader-charting
echo   C:\trading-projects\momentum-trader-charting
IF NOT "%CHARTING_DIR%"=="" echo   %CHARTING_DIR% (configured)
echo.
echo SOLUTIONS:
echo   1. Install momentum-trader-charting to one of the above locations
echo   2. OR edit this file and set CHARTING_DIR to your install path
echo.
pause
exit /b 1

REM ============================================================================
REM ERROR: Momentum-trader not found
REM ============================================================================

:error_momentum_not_found
echo.
echo ===================================================================
echo ERROR: Momentum Trader (main app) not found
echo ===================================================================
echo.
echo The charting app requires the main momentum-trader app.
echo.
echo Searched these locations:
echo   %USERPROFILE%\trading-projects\momentum-trader
echo   %USERPROFILE%\Documents\trading-projects\momentum-trader
echo   %USERPROFILE%\momentum-trader
echo   C:\trading-projects\momentum-trader
IF NOT "%MOMENTUM_DIR%"=="" echo   %MOMENTUM_DIR% (configured)
echo.
echo SOLUTIONS:
echo   1. Install momentum-trader to one of the above locations
echo   2. OR edit this file and set MOMENTUM_DIR to your install path
echo.
pause
exit /b 1
